# **1주차 복습과제**
- 1주차 복습과제는 **넘파이/판다스 연습문제**입니다.
- 코드 작성하시고, 출력 결과까지 나오도록 실행 부탁드립니다.
  - 제출 시 파일명 본인 이름으로 변경해 주세요. ex) Week1_복습과제_OOO
- 교재에서 다루지 않은 메소드도 다수 포함되어 있지만 구글링이나 챗지피티 등을 활용해서라도 풀어주세요! 한 번씩 사용해 보면 좋을 것 같아 어려워도 문제에 포함했습니다 🤗

## **넘파이**

### 1. Import the numpy package under the name `np`.

In [150]:
import numpy as np

### 2. Print the numpy version and the configuration.

(hint: `np.__version__`, `np.show_config`)

In [151]:
print(np.__version__)
np.show_config()

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep140213194937296
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
   

### 3. Create a null vector of size 10.

#### ✅ 출력 예시


```
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
```



In [152]:
# np.zeros(개수)는 모든 요소가 0.인 1차원 ndarray를 생성함
# 또는 np.zeros(shape튜플)
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 4. Create a null vector of size 10 but the fifth value which is 1.

#### ✅출력 예시


```
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
```

In [153]:
null_vector=np.zeros(10) # 크기가 10인 널 벡터 생성
null_vector[4]=1 # 5번째 요소를 1로 변경
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 5. Create a vector with values ranging from 10 to 49.

#### ✅출력 예시


```
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
```

In [154]:
# print(np.arange(start=10, stop=50))
print(np.arange(10, 50)) # 10부터 50개 요소를 포함하는 ndarray 생성

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 6. Reverse a vector (first element becomes last).

#### ✅출력 예시


```
[9 8 7 6 5 4 3 2 1 0]
```

In [155]:
print(np.sort(np.arange(10))[::-1]) # 크기가 10인 오름차순 연속 ndarray를 생성한 뒤, 이를 내림차순으로 정렬
# 배열을 생성 -> 정렬 -> 내림차순 정렬하여 출력하느 방법
# arr=np.arange(10)
# arr.sort()
# print(arr[::-1])

[9 8 7 6 5 4 3 2 1 0]


### 7. Create a 3x3 matrix with values ranging from 0 to 8.

#### ✅출력 예시


```
[[0 1 2]
 [3 4 5]
 [6 7 8]]
```

In [156]:
# 크기가 9인 오름차순 연속 배열을 생성하여 (3,3)으로 reshape
print(np.arange(9).reshape(3,-1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 8. Find indices of non-zero elements from [1,2,0,0,4,0].

#### ✅출력 예시


```
(array([0, 1, 4]),)
```

In [157]:
# 인덱스 반환 함수 where: 조건을 받아 참인 값들에 대한 인덱스 반환
array1 = np.array([1,2,0,0,4,0])
np.where(array1)

(array([0, 1, 4]),)

In [158]:
# 불린 인덱싱 사용
boolean_indices = (array1 != 0)
np.arange(6)[boolean_indices]

array([0, 1, 4])

### 9. Create a 3x3 identity matrix.

(hint: `np.eye`)

#### ✅출력 예시


```
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
```

In [159]:
# numpy.identity(): 단위 행렬 생성
# numpy.eye(): 단위 행렬 또는 대각 행렬 생성. 대각선 위치 조정 가능
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 10. Create a 3x3x3 array with random values.

#### ✅출력 예시


```
[[[0.30742852 0.26458726 0.85474383]
  [0.80234531 0.76268902 0.91286677]
  [0.8804109  0.51011378 0.82103555]]

 [[0.403753   0.83120234 0.15202655]
  [0.75782685 0.0732058  0.48148689]
  [0.2089428  0.44968622 0.88134184]]

 [[0.52251191 0.10738374 0.86279648]
  [0.26203911 0.42157754 0.68856833]
  [0.58133626 0.31059127 0.71354172]]]
```

In [160]:
# 넘파이 랜덤 추출 모듈: np.random
# rand(): 0~1 사이 균일 분포 추출. () 사이에 dimension을 적으면 해당 ndarray가 생성됨
print(np.random.rand(3,3,3))

[[[0.75926944 0.46229663 0.73446497]
  [0.9359389  0.58395259 0.92491284]
  [0.68418372 0.19976713 0.06133939]]

 [[0.10788014 0.14164286 0.24973784]
  [0.1059756  0.29143891 0.10832801]
  [0.17241215 0.62786507 0.76325356]]

 [[0.51736885 0.76502129 0.02304793]
  [0.15685263 0.67218527 0.44354344]
  [0.10545812 0.70219113 0.97015095]]]


### 11. Create a 10x10 array with random values and find the minimum and maximum values.

#### ✅출력 예시


```
0.018360924693465508 0.9990506368595156
```

In [161]:
# np.min(), np.max()를 사용하여 최솟값, 최댓값을 구할 수 있다
array1 = np.random.rand(10,10)
print(np.min(array1), np.max(array1))

0.004347037073349047 0.9947310125901005


### 12. Create a random vector of size 30 and find the mean value.

#### ✅출력 예시


```
0.46249036320403636
```

In [162]:
# np.mean()을 사용하여 평균을 구할 수 있다
array1 = np.random.rand(30)
print(array1.mean())

0.534934580683015


### 13. Create a 2d array with 1 on the border and 0 inside. (size: 10x10)

#### ✅출력 예시


```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
```

In [163]:
# numpy.pad(): 대상 array의 테두리에 특정 데이터를 추가해줌
# pad_width: 테두리 크기 지정
# mode: pad method를 적용하는 mode 지정 (default=constant)
# constant_values: 테두리에 채워넣을 상수값 (default=0)
array1 = np.zeros((8,8))
array1_padded = np.pad(array1, pad_width=((1,1),(1,1)), mode='constant', constant_values=1)
print(array1_padded)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 14. How to add a border (filled with 0's) around an existing array?

(hint: 인덱싱 사용)

#### ✅출력 예시


```
# before
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 # after
 [[0. 0. 0. 0. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 0. 0. 0. 0.]]

```

In [164]:
array1=np.ones((5,5))
print("# before\n", array1)

# fancy indexing 적용
array1[[0, -1], :]=0
array1[:, [0, -1]]=0
print("# after\n", array1)

# before
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
# after
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


### 15. What is the result of the following expression?

(실행 후, 결과에 대한 주석 작성해주세요. ex. 출력 결과에 대한 이유)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [165]:
0 * np.nan
# NaN(Not a Number)은 숫자가 아니기 때문에 다른 숫자들과 연산하면 결과값으로 nan이 반환됨

nan

In [166]:
np.nan == np.nan
# nan은 다른 수와 순서를 가질 수 없으므로(Unordered) 비교 연산하면 !=를 제외하고 False가 출력된다

False

In [167]:
np.inf > np.nan
# 지정 데이터타입의 최솟값, 최댓값을 넘어가면 음의 무한(-np.inf), 양의 무한(np.inf)으로 표기됨
# 마찬가지로 nan는 unordered 데이터이므로 False가 출력된다

False

In [168]:
np.nan - np.nan
# nan는 수학적으로 정의되지 않은 값이므로, nan가 다른 nan 값과 동일하다는 보장이 없다

nan

In [169]:
print(np.nan in set([np.nan]))
# in 연산자는 == 비교연산이 아닌, is 연산(객체의 ID를 비교하는 연산)을 수행하므로,
# set([np.nan])에 저장된 nan 객체와 np.nan 객체는 같은 ID를 가지고 있다.
# 따라서, 같은 nan 객체이기 때문에 True가 반환된다.
print([id(s) for s in set([np.nan])], id(np.nan))

True
[139270479445584] 139270479445584


In [170]:
print(0.3 == 3 * 0.1)
# float(부동소수점) 연산은 아주 작은 오차를 발생시킬 수 있다.
print(0.3)
print(3*0.1)

False
0.3
0.30000000000000004


### 16. Normalize a 5x5 random matrix.

(hint: (x - mean) / std)

#### ✅출력 예시


```
[[-1.4765971   0.9582795  -1.29910242  1.0250981  -0.79801651]
 [ 0.57945383 -1.28559078  0.02733238  0.99675052  1.2702088 ]
 [-0.08513084 -1.4686812  -0.78813593 -0.34559303 -1.15052328]
 [ 0.98183813 -1.41255344  0.37190169  1.05697419 -0.02668639]
 [-1.14466851  0.98911205  1.14499256  0.69454882  1.18478886]]
```

In [171]:
# 위의 normalize = Z-Score 정규화: 평균이 0, 표준편차가 1인 형태로 변환하는 방법
array1=np.random.rand(5,5)
array1=(array1-np.mean(array1))/np.std(array1)
print(array1)

# 확인
print()
print(f"평균: {np.mean(array1)}, 표준편차: {np.std(array1)}")

[[ 0.09808248  0.22314941 -0.52267542 -1.07082771  0.64791522]
 [-0.52662605 -1.67935612 -0.31184212 -0.2109337   1.13546227]
 [ 0.83187659 -0.31671521  1.6561715   0.27531188 -1.48965695]
 [ 0.77962933 -0.68343282 -1.68941265 -0.41298153  1.49500288]
 [ 1.6631496  -0.61112338  1.40054208  0.39275287 -1.07346245]]

평균: 2.1316282072803005e-16, 표준편차: 0.9999999999999999


### 17. Multiply a 5x3 matrix by a 3x2 matrix. (real matrix product)

#### ✅출력 예시


```
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
```

In [172]:
# 행렬의 곱 -> np.dot() 함수 사용
arr1=np.random.rand(5,3)
arr2=np.random.rand(3,2)
print(np.dot(arr1, arr2))

[[1.08366004 1.51785376]
 [1.01994045 1.33446846]
 [0.31033431 0.56295377]
 [0.97391787 1.41315108]
 [0.84525058 1.36825363]]


### 18. What are the result of the following expressions?

(실행 후, 결과에 대한 주석 작성해주세요. ex. 출력 결과에 대한 이유)

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [173]:
np.array(0) / np.array(0)
# np.array()에 정수 하나를 입력하면, 해당 정수를 원소로 가지는 0차원(스칼라) 배열이 생성된다.
# print(np.array(0)) 결과 0이 출력되는데, 위의 식에서 수학적으로 정의되지 않은 연산이 발생하므로 NaN가 반환된다.

<ipython-input-173-255405c31226>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


nan

In [174]:
np.array(0) // np.array(0)
# np.array(0) == 0
# 0 / 0는 부동소수점 연산을 사용하기 때문에 NaN 반환 가능
# 0 // 0은 정수형 연산일 경우, NaN 반환이 불가능하기 때문에 넘파이에서는! 0이 반환되도록 되어 있음
# (파이썬 자체에서는 Division by Zero 오류 발생)

<ipython-input-174-0c32ebbb55dd>:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [175]:
np.array([np.nan]).astype(int).astype(float)
# np.array([np.nan]).astype(int) -> int64의 최솟값인 array([-9223372036854775808])
# array[-9223372036854775808].astype(float) -> 부동소수점의 정밀도 차이로 인해 근사값으로 표현됨

<ipython-input-175-098f46cf9c51>:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

### 19. Create a 5x5 matrix with row values ranging from 0 to 4.

#### ✅ 출력 예시

```
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
```

In [176]:
array1=np.arange(5, dtype=float)

print(np.tile(array1, (5,1)))
# 배열 요소 전체를 반복 -> np.tile(배열, (axis별 반복 횟수))

print()
print(np.repeat(array1.reshape(1,-1), repeats=5, axis=0))
# 배열을 원소별로 반복 -> np.repeat(배열, repeats=반복횟수, axis=복사방향)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


### 20. Create a random vector of size 10 and sort it.

#### ✅출력 예시


```
[0.11443045 0.16715169 0.32515597 0.38374227 0.48327044 0.78728921
 0.80523192 0.85915686 0.96930939 0.99586525]

```

In [177]:
array_ran = np.sort(np.random.rand(10))
print(array_ran)

[0.07054351 0.22271514 0.39114002 0.53610421 0.60947606 0.69050253
 0.80804628 0.88013072 0.95744775 0.99745464]


## **판다스**


### 1. Import pandas under the alias `pd`.

In [178]:
import pandas as pd

### 2. Print the version of pandas that has been imported.

In [179]:
print(pd.__version__)

2.2.2


## 3~20번 문제는 아래 데이터프레임으로 진행됩니다.

Consider the following Python dictionary `data` and Python list `labels`:

``` python
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```


### 3. Create a DataFrame `df` from this dictionary `data` which has the index `labels`.


In [203]:
# 문제 풀이 전 numpy 임포트
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)

### 4. Display a summary of the basic information about this DataFrame and its data.  
(hint: there is a single method that can be called on the DataFrame)

In [204]:
df.info() # 타입, 데이터 건수, 인덱스, null 건수, 데이터 타입, 사용 메모리를 알 수 있음

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   animal    10 non-null     object 
 1   age       8 non-null      float64
 2   visits    10 non-null     int64  
 3   priority  10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes


### 5. Display a summary of the basic statistics about data of this DataFrame.  
(hint: there is a single method that can be called on the DataFrame)

In [205]:
df.describe()

age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

### 6. Return the first 3 rows of the DataFrame `df`.

In [206]:
print(df.head(3))

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no


### 7. Select just the 'animal' and 'age' columns from the DataFrame `df`.

In [207]:
df[['animal', 'age']]
# 또는
df.loc[:, ['animal', 'age']]

animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

### 8. Select the data in rows `[3, 4, 8]` **and** in columns `['animal', 'age']`.

In [208]:
df.loc[df.index[[3,4,8]], ['animal', 'age']]
# df의 인덱스 객체에서 3,4,8번째 인덱스의 명칭을 받아 rows에 지정
# 칼럼명 리스트를 columns에 지정

animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

### 9. Select only the rows where the number of visits is greater than 3.

In [209]:
df.loc[df['visits']>3]
# [조건] 또는 loc[조건]: DataFrame 불린 인덱싱

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []

### 10. Select the rows where the age is missing, i.e. it is `NaN`.

In [210]:
df.loc[df['age'].isna()] # df.isna(): 결손 데이터 여부 확인

animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

### 11. Select the rows where the animal is a cat *and* the age is less than 3.

In [211]:
df.loc[(df['animal']=='cat') & (df['age']<3)]

animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

### 12. Select the rows the age is between 2 and 4 (inclusive).  


In [212]:
df.loc[(df['age']>=2) & (df['age']<=4)]

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

### 13. Change the age in row 'f' to 1.5.

In [213]:
df.loc['f','age']=1.5
df
# df['f', 'age']는 해당 위치의 값, 행, 열을 복사!한 새로운 Series 객체를 반환한다

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

### 14. Calculate the sum of all visits in `df` (i.e. the total number of visits).

In [214]:
df['visits'].sum()

19

### 15. Calculate the mean age for each different animal in `df`.

In [215]:
df.groupby(by='animal')['age'].mean()
# 지정 칼럼으로 GroupBy된 df에 aggregation 함수를 호출하면
# 해당 칼럼을 제외한 모든 칼럼에 agg 함수 적용

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64

### 16. Append a new row 'k' to `df` with your choice of values for each column. Then delete that row to return the original DataFrame.

In [220]:
# 판다스 2.0부터 append 메소드가 삭제됨 -> loc 또는 concat 사용

new_row = pd.Series({'animal':'rabbit', 'age':4.2, 'visits':2, 'priority':'yes'}) # 새로운 행 Series 생성
# pd.concat([df, pd.DataFrame(new_row)])
df.loc['k'] = new_row
print(df)

   animal  age  visits priority
a     cat  2.5       1      yes
b     cat  3.0       3      yes
c   snake  0.5       2       no
d     dog  NaN       3      yes
e     dog  5.0       2       no
f     cat  1.5       3       no
g   snake  4.5       1       no
h     cat  NaN       1      yes
i     dog  7.0       2       no
j     dog  3.0       1       no
k  rabbit  4.2       2      yes


In [221]:
df.drop('k', axis=0, inplace=True)
print(df)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no


### 17. Count the number of each type of animal in `df`.

In [222]:
df['animal'].value_counts()
# value_counts(): 지정된 칼럼의 데이터값 건수 반환

animal
cat      4
dog      4
snake    2
Name: count, dtype: int64

### 18. Sort `df` first by the values in the 'age' in *decending* order, then by the value in the 'visits' column in *ascending* order (so row `i` should be first, and row `d` should be last).
#### ✅출력 예시

 index |animal	| age	|visits|	priority
---|---|---|---|---
i|	dog|	7.0|	2|	no
e|	dog|	5.0|	2|	no
g|	snake|	4.5|	1|	no
j|	dog|	3.0|	1|	no
b|	cat|	3.0|	3|	yes
a|	cat|	2.5|	1|	yes
f|	cat|	1.5|	3|	no
c|	snake|	0.5|	2|	no
h|	cat|	NaN|	1|	yes
d|	dog|	NaN|	3|	yes

In [223]:
df.sort_values(by=['age', 'visits'], ascending=[False, True])

animal  age  visits priority
i    dog  7.0       2       no
e    dog  5.0       2       no
g  snake  4.5       1       no
j    dog  3.0       1       no
b    cat  3.0       3      yes
a    cat  2.5       1      yes
f    cat  1.5       3       no
c  snake  0.5       2       no
h    cat  NaN       1      yes
d    dog  NaN       3      yes

### 19. The 'priority' column contains the values 'yes' and 'no'. Replace this column with a column of boolean values: 'yes' should be `True` and 'no' should be `False`.  
(hint: `map`)

In [224]:
# df.Series.map(): 딕셔너리를 이용해 값을 매핑할 수 있음
df['priority']=df['priority'].map({'yes':True, 'no':False})
df

animal  age  visits  priority
a    cat  2.5       1      True
b    cat  3.0       3      True
c  snake  0.5       2     False
d    dog  NaN       3      True
e    dog  5.0       2     False
f    cat  1.5       3     False
g  snake  4.5       1     False
h    cat  NaN       1      True
i    dog  7.0       2     False
j    dog  3.0       1     False

### 20. In the 'animal' column, change the 'snake' entries to 'python'.   

In [227]:
df['animal']=df['animal'].apply(lambda x:'python' if x=='snake' else x)

In [228]:
# 확인용 df 출력 셀
df

animal  age  visits  priority
a     cat  2.5       1      True
b     cat  3.0       3      True
c  python  0.5       2     False
d     dog  NaN       3      True
e     dog  5.0       2     False
f     cat  1.5       3     False
g  python  4.5       1     False
h     cat  NaN       1      True
i     dog  7.0       2     False
j     dog  3.0       1     False

### 21. Given a DataFrame of random numeric values:
```python
df = pd.DataFrame(np.random.random(size=(5, 3))) # this is a 5x3 DataFrame of float values
```

how do you subtract the row mean from each element in the row?

In [230]:
# 랜덤 시드 고정
np.random.seed(2025)

df = pd.DataFrame(np.random.random(size=(5, 3)))

df.sub(df.mean(axis=1), axis=0)

0         1         2
0 -0.516494  0.235870  0.280624
1  0.081768  0.024435 -0.106204
2 -0.047373 -0.212124  0.259497
3  0.115235 -0.230544  0.115309
4 -0.229731  0.498009 -0.268278